---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-1
  template:
    metadata:
      labels:
        app: backend-1
    spec:
      containers:
      - name: backend-1
        image: reverxy-backend
        imagePullPolicy: IfNotPresent
        args: ["-port", "8081", "-name", "backend-1"]
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend-1
spec:
  selector:
    app: backend-1
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-2
  template:
    metadata:
      labels:
        app: backend-2
    spec:
      containers:
      - name: backend-2
        image: reverxy-backend
        imagePullPolicy: IfNotPresent
        args: ["-port", "8082", "-name", "backend-2"]
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: backend-2
spec:
  selector:
    app: backend-2
  ports:
  - port: 8082
    targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-3
  template:
    metadata:
      labels:
        app: backend-3
    spec:
      containers:
      - name: backend-3
        image: reverxy-backend
        imagePullPolicy: IfNotPresent
        args: ["-port", "8083", "-name", "backend-3"]
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: backend-3
spec:
  selector:
    app: backend-3
  ports:
  - port: 8083
    targetPort: 8083